openapi: 3.0.0
servers:
  - url: http://localhost:8081/
info:
  title: Aalto University student API 
  version: '1.0.0'
paths:
  /students:
    get:
      summary: Return a list of students
      tags:
        - Students
      operationId: app.get_students
      responses:
        '200':
          description: A JSON array of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
  /student:
    post:
      summary: Create a student
      operationId: app.post_student
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
               type: object
               properties:
                name:
                  type: string
                type:
                  type: string
                  enum:
                    - Master
                    - Bachelor 


      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
components:
  parameters:
    name:
      name: name
      description: Name of the student
      in: query
      required: true
      schema:
        type: string
        pattern: '^[a-zA-Z0-9-]+$'
    type:
      name: type
      description: Type of the student
      in: query
      required: true
      schema:
        type: string
        enum:
          - Master
          - Bachelor  
  schemas:
    Student:
      type: object
      required:
        - name
        - type
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier
          example: '1'
          readOnly: true
        name:
          type: string
          description: students's name
          example: John Doe
          minLength: 1
          maxLength: 100
        type:
          type: string
          description: what level student, e.g., Bachelor or Master
          example: Master
          minLength: 1
        created:
          type: string
          format: date-time
          description: Creation time
          example: '2019-07-07T15:49:51.230+02:00'
          readOnly: true
    Students:
      type: array
      items:
        $ref: "#/components/schemas/Student"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

